services:
  api:
    build: .
    ports:
      - "8090:8080"
    depends_on:
      - db
    environment:
      - GIN_MODE=release
    volumes:
      - ./data-contracts:/data-contracts

  db:
    image: ghusta/postgres-world-db:2.12
    ports:
      - "5432:5432"
