services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - world-db
      - sakila-db
      - playground-db
    environment:
      - GIN_MODE=release
    volumes:
      - ./data-contracts:/data-contracts
      - ./connectors:/connectors

  world-db:
    image: ghusta/postgres-world-db:2.12
    ports:
      - "5432:5432"

  sakila-db:
    image: sakiladb/mysql:8
    ports:
      - "3306:3306"

  playground-db:
    build:
      context: ../sat-playground-db
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password

  axis-ui:
    build:
      context: ../axis-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://api:8080/api
    depends_on:
      - api

  axis-ai-chatbot:
    build:
      context: ../axis-ai
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY={YOUR_OPENAI_API_KEY}
      - API_BASE_URL=http://api:8080/api
